pub enum KeywordKind {
    Auto,
    Break,
    Case,
    Char,
    Const,
    Continue,
    Default,
    Do,
    Double,
    Else,
    Enum,
    Extern,
    Float,
    For,
    Goto,
    If,
    Inline,
    Int,
    Long,
    Register,
    Restrict,
    Return,
    Short,
    Signed,
    Sizeof,
    Static,
    Struct,
    Switch,
    Typedef,
    Union,
    Unsigned,
    Void,
    Volatile,
    While,
    AlignAs,
    AlignOf,
    Atomic,
    Bool,
    Complex,
    Generic,
    Imaginary,
    NoReturn,
    StaticAssert,
    ThreadLocal,
}

impl From<&str> for KeywordKind {
    fn from(value: &str) -> Self {
        match value {
            "auto" => Self::Auto,
            "break" => Self::Break,
            "case" => Self::Case,
            "char" => Self::Char,
            "const" => Self::Const,
            "continue" => Self::Continue,
            "default" => Self::Default,
            "do" => Self::Do,
            "double" => Self::Double,
            "else" => Self::Else,
            "enum" => Self::Enum,
            "extern" => Self::Extern,
            "float" => Self::Float,
            "for" => Self::For,
            "goto" => Self::Goto,
            "if" => Self::If,
            "inline" => Self::Inline,
            "int" => Self::Int,
            "long" => Self::Long,
            "register" => Self::Register,
            "restrict" => Self::Restrict,
            "return" => Self::Return,
            "short" => Self::Short,
            "signed" => Self::Signed,
            "sizeof" => Self::Sizeof,
            "static" => Self::Static,
            "struct" => Self::Struct,
            "switch" => Self::Switch,
            "typedef" => Self::Typedef,
            "union" => Self::Union,
            "unsigned" => Self::Unsigned,
            "void" => Self::Void,
            "volatile" => Self::Volatile,
            "while" => Self::While,
            "AlignAs" => Self::AlignAs,
            "AlignOf" => Self::AlignOf,
            "Atomic" => Self::Atomic,
            "Bool" => Self::Bool,
            "Complex" => Self::Complex,
            "Generic" => Self::Generic,
            "Imaginary" => Self::Imaginary,
            "NoReturn" => Self::NoReturn,
            "StaticAssert" => Self::StaticAssert,
            "ThreadLocal" => Self::ThreadLocal,

            _ => panic!("Attempted to coerce invalid string into keyword kind: {value}"),
        }
    }
}


